apiVersion: v1
entries:
  aikido-atemi-service:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-10-15T16:58:05.1993297-03:00
    description: A Helm chart for aikido-atemi-service
    digest: ffac5043ea7e3f99df5bae8607f42a81ebf284a34e418d419ba49fd7b9c08685
    name: aikido-atemi-service
    urls:
    - https://github.com/cerqueiraedu/aikido-app-charts/aikido-atemi-service/aikido-atemi-service-1.0.0.tgz
    version: 1.0.0
  aikido-randori-service:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-10-15T16:58:05.2003268-03:00
    description: A Helm chart for aikido-randori-service
    digest: 83b7fead0a2f664500d153d922c49dd73e2fb306bbad9b571312f783075e5d28
    name: aikido-randori-service
    urls:
    - https://github.com/cerqueiraedu/aikido-app-charts/aikido-randori-service/aikido-randori-service-1.0.0.tgz
    version: 1.0.0
  aikido-technique-service:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-10-15T16:58:05.2013277-03:00
    description: A Helm chart for aikido-technique-service
    digest: 4bf4db79375d3a87d7ae47a942a42f0c2fc5a2cd3bb4508a0f1b3cc6eb0d3065
    name: aikido-technique-service
    urls:
    - https://github.com/cerqueiraedu/aikido-app-charts/aikido-technique-service/aikido-technique-service-1.0.0.tgz
    version: 1.0.0
generated: 2018-10-15T16:58:05.1983292-03:00
