apiVersion: v1
entries:
  atemi-service:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-09-24T10:07:58.0381746-03:00
    description: A Helm chart for atemi-service
    digest: c0f5e6c8f0f1575e4cd8d9bc64908c1eebad44ba707555b22c88646ca3aca826
    name: atemi-service
    urls:
    - https://cerqueiraedu.github.io/aikido-app-charts/charts/atemi-service/atemi-service-1.0.0.tgz
    version: 1.0.0
  randori-service:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-09-24T10:07:58.0381746-03:00
    description: A Helm chart for randori-service
    digest: c86d8a50842cfd323892c13ef9679b79911fd7101252a62375513e373674d974
    name: randori-service
    urls:
    - https://cerqueiraedu.github.io/aikido-app-charts/charts/randori-service/randori-service-1.0.0.tgz
    version: 1.0.0
  technique-service:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-09-24T10:07:58.0391694-03:00
    description: A Helm chart for technique-service
    digest: 5eb0b89355b999773a1fbafa55629a1883c189bf91c85e1bc375e27ba750169c
    name: technique-service
    urls:
    - https://cerqueiraedu.github.io/aikido-app-charts/charts/technique-service/technique-service-1.0.0.tgz
    version: 1.0.0
generated: 2018-09-24T10:07:58.0371729-03:00
