apiVersion: v1
entries:
  atemi-service:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-10-11T14:15:31.5323388-03:00
    description: A Helm chart for atemi-service
    digest: 22f24292b3ae31037aecb93deb1ba802f880a0d1f3726f1869b002b4414d8091
    name: atemi-service
    urls:
    - https://cerqueiraedu.github.io/aikido-app-charts/charts/atemi-service/atemi-service-1.0.0.tgz
    version: 1.0.0
  randori-service:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-10-11T14:15:31.5333359-03:00
    description: A Helm chart for randori-service
    digest: 3fec4c8b83a7f5a0e28dc6be3bb3b1cfc0b9995459f0a0086e3a8aea4df82157
    name: randori-service
    urls:
    - https://cerqueiraedu.github.io/aikido-app-charts/charts/randori-service/randori-service-1.0.0.tgz
    version: 1.0.0
  technique-service:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-10-11T14:15:31.5338373-03:00
    description: A Helm chart for technique-service
    digest: 264e4fa2e89765d023b5acf66869c2de02d7d31d1b2f1c43f11ac6ff623a7f05
    name: technique-service
    urls:
    - https://cerqueiraedu.github.io/aikido-app-charts/charts/technique-service/technique-service-1.0.0.tgz
    version: 1.0.0
generated: 2018-10-11T14:15:31.5308365-03:00
