apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
    app: {{ template "atemi-service.name" . }}
    chart: {{ template "atemi-service.chart" . }}
    app.kubernetes.io/instance: "{{ $.Release.Name }}"
    app.kubernetes.io/managed-by: "{{ $.Release.Service }}"
    app.kubernetes.io/name: {{ template "atemi-service.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque 
data:
    password: {{ .Values.secretValue | quote }}