replicaCount: 2

image:
  repository: ecerqueira/technique-service
  tag: "3.1.0"
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 8081

ingress:  
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
  enabled: true
  path: /aikido/nage
  servicePort: 8081
  hosts:
    - technique-service.local