apiVersion: v1
entries:
  randori-service:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-09-05T10:54:16.7918005-03:00
    description: A Helm chart for technique-service
    digest: 0833caf8de66b8a69e2e7e26a0fea95032075b4d7591aa678863f2e4506bca0a
    name: randori-service
    urls:
    - https://cerqueiraedu.github.io/aikido-app-charts/charts/randori-service/randori-service-1.0.0.tgz
    version: 1.0.0
generated: 2018-09-17T13:25:20.7202227-03:00