replicaCount: 2

image:
  repository: ecerqueira/randori-service
  tag: "7.1.0"
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 8089

ingress:  
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
  enabled: true
  path: /aikido/randori
  servicePort: 8089
  hosts:
    - randori-service.local